export const criticalRoutes = [
  ['hub-home', '/'],
  ['hub-all-maps', '/allmaps'],
  ['hub-ee-maps', '/easter-eggs'],
  ['side-ee-list', '/side-easter-eggs'],
  ['side-ee-origins-speedrun', '/side-easter-eggs/origins-speedrun'],
  ['side-ee-kino', '/side-easter-eggs/kino'],
  ['side-ee-gorod', '/side-easter-eggs/gk'],
  ['side-ee-de', '/side-easter-eggs/de'],
  ['side-ee-shadows', '/side-easter-eggs/soe'],

  ['origins-main', '/maps/origins'],
  ['origins-fire', '/maps/origins/fire-staff'],
  ['origins-ice', '/maps/origins/ice-staff'],
  ['origins-wind', '/maps/origins/wind-staff'],
  ['origins-lightning', '/maps/origins/lightning-staff'],

  ['mob-main', '/maps/mob-of-the-dead'],
  ['mob-plane', '/maps/mob-of-the-dead/plane'],
  ['mob-retriever-skulls', '/maps/mob-of-the-dead/retriever-skulls'],
  ['mob-codes', '/maps/mob-of-the-dead/codes'],
  ['mob-final-step', '/maps/mob-of-the-dead/final-step'],

  ['shadows-main', '/maps/shadows-of-evil'],

  ['de-main', '/maps/der-eisendrache'],
  ['de-parts', '/maps/der-eisendrache/parts'],
  ['de-wisps', '/maps/der-eisendrache/wisps'],
  ['de-boss', '/maps/der-eisendrache/boss'],
  ['de-bows', '/maps/der-eisendrache/bows'],
  ['de-bow-base', '/maps/der-eisendrache/bows/base'],
  ['de-bow-electric', '/maps/der-eisendrache/bows/electric'],
  ['de-bow-fire', '/maps/der-eisendrache/bows/fire'],
  ['de-bow-wolf', '/maps/der-eisendrache/bows/wolf'],
  ['de-bow-void', '/maps/der-eisendrache/bows/void'],

  ['zets-main', '/maps/zetsubou-no-shima'],
  ['zets-prerequisites', '/maps/zetsubou-no-shima/prerequisites'],
  ['zets-blueprint', '/maps/zetsubou-no-shima/reveal-blueprint'],
  ['zets-cogs', '/maps/zetsubou-no-shima/cogs'],
  ['zets-cog-1', '/maps/zetsubou-no-shima/cogs/1'],
  ['zets-cog-2', '/maps/zetsubou-no-shima/cogs/2'],
  ['zets-cog-3', '/maps/zetsubou-no-shima/cogs/3'],
  ['zets-buildables', '/maps/zetsubou-no-shima/buildables'],
  ['zets-elevator', '/maps/zetsubou-no-shima/elevator-battle'],
  ['zets-extras', '/maps/zetsubou-no-shima/extras'],

  ['gorod-main', '/maps/gorod-krovi'],
  ['gorod-trophies', '/maps/gorod-krovi/trophies'],
  ['gorod-valves', '/maps/gorod-krovi/valves'],
  ['gorod-buildables', '/maps/gorod-krovi/buildables'],
  ['gorod-boss', '/maps/gorod-krovi/boss'],

  ['revelations-main', '/maps/revelations'],
  ['revelations-apothicon', '/maps/revelations/apothicon-upgrade'],
  ['revelations-eggs', '/maps/revelations/egg-locations'],
  ['revelations-key', '/maps/revelations/summoning-key'],
  ['revelations-sound', '/maps/revelations/sound-step'],
];

export const criticalRoutePaths = criticalRoutes.map(([, route]) => route);
